-- MySQL Script generated by MySQL Workbench
-- Tue May  3 20:26:41 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crescent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crescent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crescent` ;
USE `crescent` ;

-- -----------------------------------------------------
-- Table `crescent`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crescent`.`client` (
  `_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `userId` INT NULL,
  `age` INT NULL,
  `gender` TINYTEXT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crescent`.`buddy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crescent`.`buddy` (
  `_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `userId` INT NULL,
  `food` INT NULL,
  `navigate` INT NULL,
  `beauty` INT NULL,
  `play` INT NULL,
  `shopping` INT NULL,
  `medical` INT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crescent`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crescent`.`client` (
  `_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `userId` INT NULL,
  `age` INT NULL,
  `gender` TINYTEXT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crescent`.`buddy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crescent`.`buddy` (
  `_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `userId` INT NULL,
  `food` INT NULL,
  `navigate` INT NULL,
  `beauty` INT NULL,
  `play` INT NULL,
  `shopping` INT NULL,
  `medical` INT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

